### ISSUE TITLE
Please implement this for Microsoft Edge Chromium as well

### ISSUE THREAD

**Issue by The-DarkMatter** [joaomgcd/JoinChrome#109]
Whenever I use the chrome extension on Edge chromium, it doesn't work properly. It says This Device: Undefined.
I can only send links to my android app but it is unable to receive any messages or links from the android app. Edge also supports push messages and can run in the background. Please make it fully functional on Edge.

**Comment by joaomgcd** [comment]
Hi there. The problem with the Edge Browser is that it doesn't support an API that allows it to receive push messages, which Join needs. I've reported it here: https://github.com/MicrosoftDocs/edge-developer/issues/449 . Hopefully there'll be a workaround some time!

In the meantime you could try the new desktop app: https://joaoapps.com/join/desktop/

**Comment by sillvva** [comment]
Have you tried implementing their workaround with service worker push messaging? Would that even work?

> As an alternative, we request you to use service worker push messaging as a replacement for chrome.gcm in Edge. Service worker push messaging uses Microsoft’s push messaging service in Edge and Google’s push messaging service in Chrome. Both push services implement the same IETF standards so the push messaging services should work the same. Here’s a good reference for the same: https://web-push-book.gauntface.com/introduction/.

Otherwise, it doesn't look like Join will ever be coming to Edge.

**Comment by joaomgcd** [comment]
That doesn't work for extensions as far as I know. But I have a workaround. Check here: https://github.com/joaomgcd/JoinDesktop

**Comment by felipecrs** [comment]
Hey @joaomgcd, I have a very specific use case in which only the extension would help me:

1. I use my computer for work and for personal purposes
2. I currently have 2 profiles in Chrome to accomplish that
3. In the one for work, I let Join running as extension to sync the clipboard with another work machine I have remotely
4. When I'm done with the work I just close my work browser profile and the sync is paused (I don't let Chrome run in the background).

This way I enable Join to sync my clipboard only when I'm working. I have different accounts for Join, one for personal use and another for work related uses. Now, I would like to start working in Edge, while keeping Chrome as my personal browser, and since it's not supported by Join (the extension), I can't.

Some issues with the Desktop app would be:

1. Not multi-account
2. How would I make it stop syncing the clipboard easily when I'm done with the work (assuming multi accounts were possible)
3. Easiness of install: the extension installs automatically as I'm syncing my Chrome/Edge settings

Anyway, this is just an explanation on the use cases on where being able to use Join in the new Edge would be super helpful.

**Comment by joaomgcd** [comment]
Thanks for the explanation. Unfortunately for the reasons mentioned above it's not possible to receive pushes in Edge extensions in the same way that it works for Chrome extensions.

**Comment by vivekrp** [comment]
Are any fixes for this? Using the new Edge Dev browser for Bing AI and Join doesn't work. It's showing "This device:
undefined"
