### ISSUE TITLE
SMS message deleted by Join

### ISSUE THREAD

**Issue by HomeDipo** [joaomgcd/JoinChrome#74]
Hello,

For some reason when I get texts and open them in Join for Chrome, it occasionally will delete the text message. For some reason the texts in Join are not syncing properly with the texts on my phone and Join is overwriting the texts on my phone so now I can't use the text feature without worrying about losing my texts. Any idea how to fix this?

**Comment by joaomgcd** [comment]
Hi. Please check that your SMS app doesn't have an open to delete texts on notification dismissal. Join can't delete texts on your device because in Android only default SMS apps can do that, and Join is not a default SMS app.

If all else fails, try using a different SMS app and see if that works.

Just to reiterate, it's not possible for Join to delete SMS messages. Hope this clarifies it.

**Comment by HomeDipo** [comment]
The thing is, Join at times doesn't update the text messages on the extension. There are times I will send a text in Join and it updates but then when I receive a text it glitches and Join only shows texts from a day ago instead. After that, I check my phone and all my texts are rolled back.

**Comment by joaomgcd** [comment]
Again, Join can't really change messages on your phone. It's read-only. If the messages are gone from your phone then it's normal that they don't appear in Join as well... Sorry!
